
<field:language itemname="语言" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="国语,粤语,英语"  maxlength="50" page="">
</field:language>

<field:pfz itemname="评分值" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="6" page="">
</field:pfz>

<field:area itemname="地区" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="大陆,港台,欧美,日韩"  maxlength="50" page="">
</field:area>

<field:year itemname="年代" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="4" page="">
</field:year>

<field:director itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:director>

<field:mainactors itemname="主演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:mainactors>

<field:introduce itemname="剧情介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="1024" page="">
</field:introduce>

