<li class="d[field:global.autoindex/]">
						<a href="[field:arcurl/]" target="_blank">
							<img src="[field:litpic/]" title="[field:title/]" />
						</a>
						<p>[field:language/]---</p>
						<b>
							<a href="[field:arcurl/]" target="_blank">[field:title/]</a>
							
							<script src="[field:phpurl/]/get_stars.php?id=[field:id/]" type='text/javascript' language="javascript"></script>
						</b>
					</li>