
<field:language itemname="语言" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="国语,粤语,英语"  maxlength="50" page="">
</field:language>

<field:pfz itemname="评分值" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="6" page="">
</field:pfz>

<field:area itemname="地区" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="大陆,港台,欧美,日韩"  maxlength="50" page="">
</field:area>
