<?php
$z[0]=Array("noteinfo","",0,215);
$z[0][4]['notename']="搜狐视频网站-电影采集点";
$z[0][4]['channelid']="18";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://vod.kankan.com/v/73/73762.shtml";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<ul class=\"movielist\" id=\"movie_list\">{/dede:areastart}\r\n    {dede:areaend}<p class=\"list-pager-v2\">{/dede:areaend}\r\n",219,695);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://movie.kankan.com/type,order/movie,hits/page(*)/";
$z[1][4]['startid']="2";
$z[1][4]['endid']="4";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>