<ul>
					<li class="pic">
						<a href="[field:arcurl/]" target="_blank"><img title="[field:title/]" src="[field:litpic/]" /></a>
					</li>
					<li class="title">
						<a href="[field:arcurl/]" target="_blank">[field:title/]</a>
					</li>
					<li class="info">
						<img src="[field:global.cfg_templets_skin/]/images/1.jpg" /> [field:pfz/]分
					</li>
					<li class="cont" style="height: 105px; overflow: hidden; text-overflow: ellipsis;">[field:introduce/] </li>
				</ul>