<?php
$z[0]=Array("global","",42,67);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n			<!--\r\n				大家注意：typeurl并不是dede_arctype表中的字段,它是在程序中临时计算得到的\r\n				(channel标签定义的文件中GetOneTypeUrlA()函数生成的typeurl)\r\n			-->\r\n			<li>\r\n				<a href=\"[field:typelink/]\" title=\"[field:typename/]\" target=\"_self\">[field:typename /]</a>\r\n		    </li> \r\n		",293,676);
$z[1][4]['orderby']="id";
$z[1][4]['type']="top";
$z[1][4]['row']="8";

?>