<?php
$z[0]=Array("channel","\r\n\r\n[field:id/]==[field:typename/]  \r\n\r\n[field:typename function='md5(@me)'/]   \r\n\r\n[field:typename runphp='yes']\r\n@me = (@me!=\"\")?\"空的\":@me;\r\n[/field:typename]  \r\n\r\n[field:typename function='test_func(@me)'/]   \r\n\r\n[field:global.cfg_soft_lang/]\r\n[field:global name='cfg_soft_lang'/]\r\n\r\n<br/>",1063,1406);
$z[0][4]['type']="top";
$z[0][4]['row']="8";
$z[1]=Array("global","",1412,1440);
$z[1][4]['name']="cfg_soft_lang";

?>